version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install npm dependencies
          command: |
            npm install
            sudo npm install -g eslint
            sudo npm install -g webpack
      - run:
          name: lint javascript
          command: npm run lint
      - run:
          name: run tests
          command: npm run test
      - run:
          name: bundle for production javascript
          command: npm run build-prod
      - run:
          name: build site
          command: bundle exec jekyll build
      - run:
          name: deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/deploy-ci.sh
            fi
